 Operators = function() {var operators = {
            "^": {
                precedence: 5
            },
            "/": {
                precedence: 3
            },
            "*": {
                precedence: 4
            },
            "+": {
                precedence: 2
            },
            "-": {
                precedence: 2
            }
        };}; 

var operators = {
            "^": {
                precedence: 5
            },
            "/": {
                precedence: 3
            },
            "*": {
                precedence: 4
            },
            "+": {
                precedence: 2
            },
            "-": {
                precedence: 2
            }
        };   exports.operators = operators;
exports.Operators = Operators;
 